import pygame

maps = {}
map[1] = ["ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss",
        "ssss            ssss"]
        
        
map[2] = [ "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "sssssssss    sssssss",
            "sssssssss    sssssss",
            "sssssssss    sssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "ssssssss   sssssssss",
            "sssssss    sssssssss",
            "ssssss     sssssssss",
            "ssssss     sssssssss",
            "ssssssss    ssssssss",
            "ssssssss     sssssss",
            "sssssssss      sssss",
            "sssssssss       ssss",
            "sssssssss       ssss",
            "ssssssssss     sssss",
            "sssssssss   ssssssss",
            "ssssssss   sssssssss",
            "ssssssss   sssssssss",
            "ssssssss   sssssssss"]
        
                    
map[3] = ["sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss"]
        
        
map[4] = ["ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss"]

map[5] = ["ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "sss          sssssss",
            "sss           ssssss",
            "sss            sssss",
            "sss             ssss",
            "sss              sss",
            "sss              sss",
            "ssss             sss",
            "sssss            sss",
            "ssssss           sss",
            "sssssss          sss",
            "ssssssss         sss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss"]


map[6] = ["sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "ssss            ssss",
            "ssss            ssss",
            "ssss   ssssss   ssss",
            "ssss   ssssss   ssss",
            "ssss   ssssss   ssss",
            "ssss   ssssss   ssss",
            "ssss   ssssss   ssss",
            "ssss   ssssss   ssss",
            "ssss            ssss",
            "ssss            ssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss"]

            
map[7] = ["sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "ssss            ssss",
            "ssss            ssss",
            "ssss     ss     ssss",
            "ssss     ss     ssss",
            "ssss   ss  ss   ssss",
            "ssss   ss  ss   ssss",
            "ssss     ss     ssss",
            "ssss     ss     ssss",
            "ssss            ssss",
            "ssss            ssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss"]


map[8] = ["ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssss            ssss",
            "ssss  ss        ssss",
            "ssss  ss ss     ssss",
            "ssss     ss     ssss",
            "ssss       ss   ssss",
            "ssss  ss   ss   ssss",
            "ssss  ss        ssss",
            "ssss    ss   ss ssss",
            "ssss    ss   ss ssss",
            "ssss            ssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss",
            "sssssssss   ssssssss"]


map[9] = ["sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss    sssssssss",
            "sssssss       ssssss",
            "sssssss       ssssss",
            "sssssssss     ssssss",
            "sssssssss     ssssss",
            "sssssssss     ssssss",
            "ssssssssss   sssssss",
            "ssssssssss   sssssss",
            "ssssssssss   sssssss",
            "ssssssssss   sssssss",
            "sssssssss     ssssss",
            "sssssssss     ssssss",
            "sssssssss         ss",
            "sssssssss         ss",
            "sssssssssssss     ss",
            "sssssssssssss     ss",
            "sssssss           ss",
            "sssssss           ss",
            "sssssss    sssssssss",
            "sssssss    sssssssss"]

map[10] =["ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss"
            "ssss        ssssssss",
            "ssss        ssssssss",
            "ssss    ssssssssssss",
            "ssss    ssssssssssss",
            "ssss    ssssssssssss",
            "ssss    ssssssssssss",
            "ssss    ssssssssssss",
            "ssss    ssssssssssss",
            "ssss    ssssssssssss",
            "ssss    ssssssssssss",
            "ss      ssssssssssss",
            "ss      ssssssssssss",
            "ss    ssssssssssssss",
            "ss    ssssssssssssss",
            "ssss    ssssssssssss",
            "ssss    ssssssssssss",
            "ssssss    ssssssssss",
            "ssssss    ssssssssss",]

map[11] = ["ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss",
            "ss                ss"]

map[12] = [ "sssssss     ssssssss",
            "sssssss     ssssssss",
            "sssssss         ssss",
            "sssssss         ssss",
            "sssssssssss     ssss",
            "sssssssssss     ssss",
            "sssssssssss     ssss",
            "sssssssssss     ssss",
            "sssssssssss     ssss",
            "sssssssssss     ssss",
            "sssssssssss        s",
            "sssssssssss        s",
            "sssssssssssssssss  s",
            "sssssssssssssssss  s",
            "sssssssssssssssss  s",
            "sssssssssssssssss  s",
            "sssssssssssssssss  s",
            "ssssssssss         s",
            "ssssssssss         s",
            "ssssssssss     sssss",
            "ssssssssss     sssss",
            "ssssssss       sssss",
            "ssssssss       sssss"]
            
map[13] = ["ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ss          ssssssss",
            "ss          ssssssss",
            "ss    ssssssssssssss",
            "ss    ssssssssssssss",
            "ss    ssssssssssssss",
            "ss    ssssssssssssss",
            "ss    ssssssssssssss",
            "ss           sssssss",
            "ss           sssssss",
            "sssssssss    sssssss",
            "sssssssss    sssssss",
            "sssssssss    sssssss"]
map[14] = ["ssssssss      ssssss",
            "ssssssss      ssssss",
            "ssssssss      ssssss",
            "ssssssss      ssssss",
            "ssssssss      ssssss",
            "sss              sss",
            "sss              sss",
            "sss              sss",
            "sss              sss",
            "sss              sss",
            "sss              sss",
            "sss              sss",
            "sss              sss",
            "sss              sss",
            "sss              sss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss",
            "ssssssss    ssssssss"]

map[15] = ["ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss",
            "ssssssssssssss                     ssssssssssssss"]

self.p14 = ["ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssss                  ssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss",
            "ssssssssssssssssssssss      ssssssssssssssssssssss"]

self.p15 = ["sssssssssssssssssss     sssssssssssssssssssssssss",
            "sssssssssssssssssss     sssssssssssssssssssssssss",
            "ssssssssssssssssssss    sssssssssssssssssssssssss",
            "sssssssssssssssssssss   sssssssssssssssssssssssss",
            "ssssssssssssssssssss   ssssssssssssssssssssssssss",
            "sssssssssssssssssss    ssssssssssssssssssssssssss",
            "ssssssssssssssssss      sssssssssssssssssssssssss",
            "sssssssssssssssss        ssssssssssssssssssssssss",
            "ssssssssssssssssss      sssssssssssssssssssssssss",
            "sssssssssssssssssss   sssssssssssssssssssssssssss",
            "ssssssssssssssssssss   ssssssssssssssssssssssssss",
            "sssssssssssssssssssss   sssssssssssssssssssssssss",
            "ssssssssssssssssssss   ssssssssssssssssssssssssss",
            "ssssssssssssssssssss     ssssssssssssssssssssssss",
            "sssssssssssssssssssss     sssssssssssssssssssssss"]
            
self.p16 = ["sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssssssss    sssssssssssssssssssss",
            "ssssssssssssssssssssssssss    ssssssssssssssssssss",
            "sssssssssssssssssssssssssss    sssssssssssssssssss",
            "ssssssssssssssssssssssssss    ssssssssssssssssssss",
            "sssssssssssssssssssssssss    sssssssssssssssssssss",
            "ssssssssssssssssssssssss    ssssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssss    sssssssssssssssssssssssss",
            "ssssssssssssssssssssss    ssssssssssssssssssssssss",
            "ssssssssssssssssssssssss    ssssssssssssssssssssss",
            "ssssssssssssssssssssssssss    ssssssssssssssssssss",
            "sssssssssssssssssssssssss    sssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss"]

self.p17 = ["sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssssssss    sssssssssssssssssssss",
            "sssssssssssssssssssssssssss    sssssssssssssssssss",
            "ssssssssssssssssssssssssssss    ssssssssssssssssss",
            "sssssssssssssssssssssssss         ssssssssssssssss",
            "ssssssssssssssssssssssss            ssssssssssssss",
            "sssssssssssssssssssssss      s       sssssssssssss",
            "sssssssssssssssssssss       sss      sssssssssssss",
            "ssssssssssssssssssssss       s      ssssssssssssss",
            "ssssssssssssssssssssssss          ssssssssssssssss",
            "ssssssssssssssssssssssssss       sssssssssssssssss",
            "sssssssssssssssssssssssss      sssssssssssssssssss",
            "sssssssssssssssssssssss      sssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss",
            "sssssssssssssssssssssss    sssssssssssssssssssssss"]
